//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCalendarForUser
    {
        public int calenderNum { get; set; }
        public int id { get; set; }
        public Nullable<bool> isPrimary { get; set; }
    
        public virtual tblCalendersType tblCalendersType { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
