//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContacts
    {
        public int contactId { get; set; }
        public string contactName { get; set; }
        public string phoneNo { get; set; }
        public string mobileNo { get; set; }
        public string email { get; set; }
        public string role { get; set; }
        public string contactComment { get; set; }
        public string patientId { get; set; }
    
        public virtual tblPatient tblPatient { get; set; }
    }
}
