//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCaresForPatient
    {
        public string patientId { get; set; }
        public int workerId { get; set; }
        public string status { get; set; }
        public string linkTo { get; set; }
    
        public virtual tblPatient tblPatient { get; set; }
        public virtual tblForeignUser tblForeignUser { get; set; }
    }
}
