//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduledNotifications
    {
        public int NotificationID { get; set; }
        public string pushToken { get; set; }
        public string Title { get; set; }
        public string pushMessage { get; set; }
        public System.DateTime ScheduledTime { get; set; }
        public string Data { get; set; }
    }
}
