//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblActualTask
    {
        public int actualId { get; set; }
        public int taskId { get; set; }
        public System.TimeSpan TimeInDay { get; set; }
        public System.DateTime taskDate { get; set; }
        public string taskStatus { get; set; }
    
        public virtual tblPatientTask tblPatientTask { get; set; }
    }
}
