//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDrugForPatient
    {
        public int listId { get; set; }
        public System.DateTime fromDate { get; set; }
        public System.DateTime toDate { get; set; }
        public byte dosage { get; set; }
        public Nullable<int> qtyInBox { get; set; }
        public Nullable<byte> minQuantity { get; set; }
        public int drugId { get; set; }
        public string patientId { get; set; }
        public Nullable<System.DateTime> lastTakenDate { get; set; }
    
        public virtual tblActualList tblActualList { get; set; }
        public virtual tblDrug tblDrug { get; set; }
        public virtual tblPatient tblPatient { get; set; }
    }
}
