
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DATA
{

using System;
    using System.Collections.Generic;
    
public partial class tblForeignUser
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblForeignUser()
    {

        this.tblCaresForPatients = new HashSet<tblCaresForPatient>();

        this.tblPatientTasks = new HashSet<tblPatientTask>();

        this.tblPaymentRequests = new HashSet<tblPaymentRequest>();

        this.tblPrivateTasks = new HashSet<tblPrivateTask>();

    }


    public int Id { get; set; }

    public System.DateTime DateOfBirth { get; set; }

    public Nullable<System.DateTime> VisaExpirationDate { get; set; }

    public string LanguageName_En { get; set; }

    public string CountryName_En { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblCaresForPatient> tblCaresForPatients { get; set; }

    public virtual tblCountry tblCountry { get; set; }

    public virtual tblLanguage tblLanguage { get; set; }

    public virtual tblUser tblUser { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblPatientTask> tblPatientTasks { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblPaymentRequest> tblPaymentRequests { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblPrivateTask> tblPrivateTasks { get; set; }

}

}
