
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DATA
{

using System;
    using System.Collections.Generic;
    
public partial class tblHobbies
{

    public string patientId { get; set; }

    public string books { get; set; }

    public string music { get; set; }

    public string TVShow { get; set; }

    public string radioChannel { get; set; }

    public string food { get; set; }

    public string drink { get; set; }

    public string movie { get; set; }

    public string specialHabits { get; set; }

    public string afternoonNap { get; set; }

    public string nightSleep { get; set; }

    public string other { get; set; }



    public virtual tblPatient tblPatient { get; set; }

}

}
