
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DATA
{

using System;
    using System.Collections.Generic;
    
public partial class tblLanguage
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblLanguage()
    {

        this.tblForeignUsers = new HashSet<tblForeignUser>();

        this.tblPatients = new HashSet<tblPatient>();

    }


    public string LanguageName_En { get; set; }

    public string LanguageName_He { get; set; }

    public string LanguageName_Encode { get; set; }

    public string LanguageName_Origin { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblForeignUser> tblForeignUsers { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblPatient> tblPatients { get; set; }

}

}
