
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DATA
{

using System;
    using System.Collections.Generic;
    
public partial class tblLimitation
{

    public string patientId { get; set; }

    public string allergies { get; set; }

    public string sensitivities { get; set; }

    public string physicalAbilities { get; set; }

    public string bathRoutine { get; set; }

    public string sensitivityToNoise { get; set; }

    public string other { get; set; }



    public virtual tblPatient tblPatient { get; set; }

}

}
