//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblList()
        {
            this.tblProductList = new HashSet<tblProductList>();
        }
    
        public Nullable<int> listId { get; set; }
        public string listName { get; set; }
        public int actualId { get; set; }
        public int taskId { get; set; }
    
        public virtual tblActualList tblActualList { get; set; }
        public virtual tblActualTask tblActualTask { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductList> tblProductList { get; set; }
    }
}
