//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNotifictions
    {
        public int notificationID { get; set; }
        public string title { get; set; }
        public string pushMessage { get; set; }
        public System.DateTime time { get; set; }
        public int userId { get; set; }
        public string status { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
