
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DATA
{

using System;
    using System.Collections.Generic;
    
public partial class tblPatient
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblPatient()
    {

        this.tblCaresForPatient = new HashSet<tblCaresForPatient>();

        this.tblContacts = new HashSet<tblContacts>();

        this.tblDrugForPatient = new HashSet<tblDrugForPatient>();

        this.tblPatientTask = new HashSet<tblPatientTask>();

    }


    public string patientId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public System.DateTime DateOfBirth { get; set; }

    public int userId { get; set; }

    public string LanguageName_En { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblCaresForPatient> tblCaresForPatient { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblContacts> tblContacts { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblDrugForPatient> tblDrugForPatient { get; set; }

    public virtual tblHobbies tblHobbies { get; set; }

    public virtual tblLanguage tblLanguage { get; set; }

    public virtual tblLimitations tblLimitations { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblPatientTask> tblPatientTask { get; set; }

    public virtual tblUser tblUser { get; set; }

}

}
