//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPaymentRequest
    {
        public int requestId { get; set; }
        public string requestSubject { get; set; }
        public double amountToPay { get; set; }
        public System.DateTime requestDate { get; set; }
        public string requestProofDocument { get; set; }
        public string requestComment { get; set; }
        public string requestStatus { get; set; }
        public int userId { get; set; }
    
        public virtual tblForeignUser tblForeignUser { get; set; }
    }
}
