
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DATA
{

using System;
    using System.Collections.Generic;
    
public partial class tblProductList
{

    public int productId { get; set; }

    public int listId { get; set; }

    public string productStatus { get; set; }



    public virtual tblList tblList { get; set; }

    public virtual tblProduct tblProduct { get; set; }

}

}
