//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblScheduledNotifications
    {
        public int notificationID { get; set; }
        public string pushToken { get; set; }
        public string title { get; set; }
        public string pushMessage { get; set; }
        public System.DateTime scheduledTime { get; set; }
        public string data { get; set; }
        public Nullable<int> actualTaskId { get; set; }
        public Nullable<int> paymentId { get; set; }
        public Nullable<int> taskId { get; set; }
    }
}
